# Generated by Django 4.1 on 2022-08-30 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='stadium',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lineups', models.TextField(blank=True)),
                ('club1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_club', to='clubs.club')),
                ('club2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_club', to='clubs.club')),
            ],
        ),
    ]
