# Generated by Django 4.1 on 2022-08-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_stadium_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('Super', 'Superliga'), ('K', 'Kubok')], default='Super', max_length=15),
        ),
    ]
