# Generated by Django 4.1 on 2022-08-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_match_match_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('Superliga', 'Superliga'), ('Kubok', 'Kubok')], default='Superliga', max_length=15),
        ),
    ]
