# Generated by Django 4.1 on 2022-08-30 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_remove_player_club_club_players_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='players',
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='clubs.club'),
            preserve_default=False,
        ),
    ]
