# Generated by Django 4.1 on 2022-08-30 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_result_draw_result_goals_result_lost_result_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='club1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_match', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='match',
            name='club2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_match', to='clubs.club'),
        ),
    ]
