# Generated by Django 4.1 on 2022-09-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_round_match_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
