# Generated by Django 4.1 on 2022-09-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_alter_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='club1_g_p',
            field=models.ManyToManyField(blank=True, to='clubs.player'),
        ),
    ]
