# Generated by Django 4.1 on 2022-09-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_match_club1_g_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='club1_g_p',
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
    ]
