# Generated by Django 4.1 on 2022-09-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_remove_match_club1_g_p_player_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goal_player',
            field=models.ManyToManyField(blank=True, to='clubs.player'),
        ),
    ]
