# Generated by Django 4.1 on 2022-09-18 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_match_goal_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.player')),
            ],
        ),
    ]
