# Generated by Django 4.1 on 2022-09-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_playerscored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscored',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scored', to='clubs.player'),
        ),
    ]
