# Generated by Django 4.1 on 2022-09-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Goalkeeper', 'goalkeeper'), ('Midfielder', 'midfielder'), ('Defender', 'defender'), ('Forward', 'forward')], default='Forward', max_length=15),
        ),
    ]
